.\" Build Tool Example
.\" Copyright (C) 2024 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd June 17, 2024
.Dt example 1
.Os example
.\" ###### Name #############################################################
.Sh NAME
.Nm example
.Nd An example program
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm example
.Op Fl \-version|\-v
.\" ###### Description ######################################################
.Sh DESCRIPTION
This is a simple example program, written in C++ together with an example
library.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It  \-\-version|\-v
Just prints package version and exists.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It example
.It example --version
.It example -v
.El
